/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "coursereg.h"
courses c[100];
int * admit_1_svc(struct arg *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct word *
view_1_svc(struct word *argp, struct svc_req *rqstp)
{
	static struct word  result;

	/*
	 * insert server code here
	 */

	return &result;
}
