/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COURSEREG_H_RPCGEN
#define _COURSEREG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct word {
	char str[100];
};
typedef struct word word;

struct courses {
	char name[100];
	char faculty[100];
	struct word students[100];
	int size;
};
typedef struct courses courses;

struct arg {
	char studentName[100];
	char courseName[100];
};
typedef struct arg arg;

#define coursereg 0x23451111
#define COURSEREG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define admit 1
extern  int * admit_1(struct arg *, CLIENT *);
extern  int * admit_1_svc(struct arg *, struct svc_req *);
#define view 2
extern  struct word * view_1(struct word *, CLIENT *);
extern  struct word * view_1_svc(struct word *, struct svc_req *);
extern int coursereg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define admit 1
extern  int * admit_1();
extern  int * admit_1_svc();
#define view 2
extern  struct word * view_1();
extern  struct word * view_1_svc();
extern int coursereg_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_word (XDR *, word*);
extern  bool_t xdr_courses (XDR *, courses*);
extern  bool_t xdr_arg (XDR *, arg*);

#else /* K&R C */
extern bool_t xdr_word ();
extern bool_t xdr_courses ();
extern bool_t xdr_arg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COURSEREG_H_RPCGEN */
