/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"


void
fact_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  factorial_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, fact, FACT_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	while(361) {
		int choice;
		printf("Enter a choice:\n1.Compute factorial\n2.Exit\n");
		scanf("%d",&choice);
		if(choice==1) {
			int num;
			printf("Enter a number: ");
			scanf("%d",&num);
			factorial_1_arg = num;
			result_1 = factorial_1(&factorial_1_arg, clnt);
			if (result_1 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			else {
				printf("The factorial of the number is: %d\n",*result_1);
			}
		}
		else {
			exit(0);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	fact_1 (host);
exit (0);
}
