/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DICT_H_RPCGEN
#define _DICT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct word {
	char s[100];
};
typedef struct word word;

#define dict 0x23451111
#define DICT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define search 1
extern  word * search_1(word *, CLIENT *);
extern  word * search_1_svc(word *, struct svc_req *);
extern int dict_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define search 1
extern  word * search_1();
extern  word * search_1_svc();
extern int dict_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_word (XDR *, word*);

#else /* K&R C */
extern bool_t xdr_word ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DICT_H_RPCGEN */
