/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dict.h"
void
dict_1(char *host) 
{
	CLIENT *clnt;
	word  *result_1;
	word  search_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, dict, DICT_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	char cache[100][100];
	char meaning[100][100];
	int cache_size = 0;
	while(361) {
		int choice;
		printf("1. Search for a word\n2. Exit\n");
		scanf("%d",&choice);
		if(choice==1) {
			int flag = 0;
			char finder[100];
			printf("Enter the word to be searched\n");
			scanf("%s",finder);
			printf("The word searched is: %s\n",finder);
			for(int i=0;i<cache_size;i++) {
				if(strcmp(cache[i],finder)==0) {
					printf("Word found in cache\n");
					printf("The meaning is: %s\n",meaning[i]);
					flag = 1;
					break;
				}
			}
			if(flag==0) {
				strcpy(search_1_arg.s,finder);
				result_1 = search_1(&search_1_arg, clnt);
				if (result_1 == (word *) NULL) {
				clnt_perror (clnt, "call failed");
				}
				else {
					printf("Word not found in cache!\n");
					if(strcmp(result_1->s,"NF")==0) {
						printf("Word was not found!\n");
						continue;
					}
					printf("The meaning retrieved from server is: %s\n",result_1->s);
					printf("Length is: %ld\n",strlen(result_1->s));
					strcpy(cache[cache_size],finder);
					strcpy(meaning[cache_size],result_1->s);
					cache_size++;
					if(cache_size==101) {
						printf("Cache full!!\n");
						cache_size -= 5;
						printf("Deleting last 5 value!\n");
						printf("Freed up last 5 values successfully!\n");
					}
				}
			}
		}
		if(choice==2) {
			exit(0);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	dict_1 (host);
exit (0);
}
