/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
	
#include "dict.h"

word *
search_1_svc(word *argp, struct svc_req *rqstp)
{
	static word result;
	char words[100][100] = {"socket","blockchain","queue","database","UPS"};
	char meaning[100][100] = {"Programming in networks","Decentralized network","A data structure","Storehouse of data","Backup battery"};
	int index = -1;
	printf("Searching for the word...%s\n",argp->s);
	for(int i=0;i<100;i++) {
		if(strcmp(words[i],argp->s)==0) {
			index = i;
			break;
		}
	}
	if(index==-1) {
		printf("Word not found!\n");
		char ret[100] = "NF";
		strcpy(result.s,ret);
	}
	else {
		printf("Word found!\n");
		strcpy(result.s,meaning[index]);
		printf("The meaning returned is: %s\n",meaning[index]);
	}
	return &result;
}
