/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct question {
	char q[1000];
};
typedef struct question question;

struct leader {
	char names[100];
	int mark;
};
typedef struct leader leader;

struct qanda {
	int q;
	int a;
};
typedef struct qanda qanda;

struct name {
	char n[100];
};
typedef struct name name;

#define test 0x23451111
#define TEST_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define intialize 1
extern  void * intialize_1(name *, CLIENT *);
extern  void * intialize_1_svc(name *, struct svc_req *);
#define request 2
extern  question * request_1(int *, CLIENT *);
extern  question * request_1_svc(int *, struct svc_req *);
#define judge 3
extern  void * judge_1(qanda *, CLIENT *);
extern  void * judge_1_svc(qanda *, struct svc_req *);
#define score 4
extern  int * score_1(name *, CLIENT *);
extern  int * score_1_svc(name *, struct svc_req *);
#define leaderboard 5
extern  leader * leaderboard_1(int *, CLIENT *);
extern  leader * leaderboard_1_svc(int *, struct svc_req *);
extern int test_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define intialize 1
extern  void * intialize_1();
extern  void * intialize_1_svc();
#define request 2
extern  question * request_1();
extern  question * request_1_svc();
#define judge 3
extern  void * judge_1();
extern  void * judge_1_svc();
#define score 4
extern  int * score_1();
extern  int * score_1_svc();
#define leaderboard 5
extern  leader * leaderboard_1();
extern  leader * leaderboard_1_svc();
extern int test_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_question (XDR *, question*);
extern  bool_t xdr_leader (XDR *, leader*);
extern  bool_t xdr_qanda (XDR *, qanda*);
extern  bool_t xdr_name (XDR *, name*);

#else /* K&R C */
extern bool_t xdr_question ();
extern bool_t xdr_leader ();
extern bool_t xdr_qanda ();
extern bool_t xdr_name ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_H_RPCGEN */
