/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "test.h"
#define N 3

char names[100][100];
int scores[100] = {0};
int countPpl = 0;
char questions[100][1000] = {"Where is PSG Tech?\n1.CBE\n2.MAS\n3.PUD\n4.KAN","Where is SVMHSS?\n1.UDT\n2.CBE\n3.MAS\n4.POC","Who is who?\n1.W\n2.L\n3.R\n4.W"};
int answers[100] = {0};

void *
intialize_1_svc(name *argp, struct svc_req *rqstp)
{
	static char * result;
	answers[0] = 0;
	answers[1] = 0;
	answers[2] = 1;
	printf("Questions initialized and ready to be served!\n");
	strcpy(names[countPpl],argp->n);
	return (void *) &result;
}

question *
request_1_svc(int *argp, struct svc_req *rqstp)
{
	printf("Sending a question!\n");
	static question  result;
	strcpy(result.q,questions[*argp]);
	return &result;
}

void *
judge_1_svc(qanda *argp, struct svc_req *rqstp)
{
	static char * result;
	if(answers[argp->q]==argp->a) {
		scores[countPpl]++;
	}
	if(argp->q==N-1) {
		countPpl++;
	}
	return (void *) &result;
}

int *
score_1_svc(name *argp, struct svc_req *rqstp)
{
	printf("Score released!\n");
	static int  result;
	int index = -1;
	for(int i=0;i<countPpl;i++) {
		if(strcmp(names[i],argp->n)==0) {
			index = i;
			break;
		}
	}
	if(index==-1) {
		result = -1;
	}
	else {
		result = scores[index];
	}
	return &result;
}

leader *
leaderboard_1_svc(int *argp, struct svc_req *rqstp)
{
	static leader  result;
	if(*argp==0) {
		printf("Leaderboard released!\n");
	}
	if(*argp >= countPpl) {
		result.mark = -1;
	}
	else {
		strcpy(result.names,names[*argp]);
		result.mark = scores[*argp];
	}
	return &result;
}
