/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test.h"
#define N 3

void
test_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	name  intialize_1_arg;
	question  *result_2;
	int  request_1_arg;
	void  *result_3;
	qanda  judge_1_arg;
	int  *result_4;
	name  score_1_arg;
	leader  *result_5;
	int  leaderboard_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, test, TEST_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif
	while(361) {
		printf("1.Start your test\n2.Show Leaderboard\n3.Exit\n");
		int choice;
		scanf("%d",&choice);
		if(choice==1) {
			printf("Enter your sweet name\n");
			scanf("%s",intialize_1_arg.n);
			result_1 = intialize_1(&intialize_1_arg, clnt);
			if (result_1 == (void *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			else {
				printf("Starting your test\n");
				for(int i=0;i<N;i++) {
					request_1_arg = i;
					result_2 = request_1(&request_1_arg, clnt);
					if (result_2 == (question *) NULL) {
						clnt_perror (clnt, "call failed");
					}
					else {
						int option;
						printf("\nYour question %d\n",i+1);
						printf("%s",result_2->q);
						printf("\nEnter your choice: ");
						scanf("%d",&option);
						judge_1_arg.q = i;
						judge_1_arg.a = option%4;
						result_3 = judge_1(&judge_1_arg, clnt);
						if (result_3 == (void *) NULL) {
							clnt_perror (clnt, "call failed");
						}
					}
				}
				printf("Your test is completed now\n");
				strcpy(score_1_arg.n,intialize_1_arg.n);
				result_4 = score_1(&score_1_arg, clnt);
				if (result_4 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				printf("Your score is: %d\n",*result_4);
				printf("You answered %d out of %d questions\n",*result_4,N);
				int sc = *result_4;
				printf("Your accuracy is: %f\n",(float)sc/(float)N);
			}
		}
		else if(choice==2) {
			int cur = 0;
			leaderboard_1_arg = cur;
			printf("\nName\tScore\n");
			while(361) {
				result_5 = leaderboard_1(&leaderboard_1_arg, clnt);
				if (result_5 == (leader *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				if(result_5->mark==-1) {
					break;
				}
				else {
					printf("%s\t%d\n",result_5->names,result_5->mark);
					leaderboard_1_arg = ++cur;
				}
			}
			printf("\n");
		}
		else {
			printf("Thank you!\n");
			exit(0);
		}
	}

	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	test_1 (host);
exit (0);
}
	