/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PHONE_H_RPCGEN
#define _PHONE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct customer {
	char name[100];
	char phone_number[10];
	char address[100];
};
typedef struct customer customer;

struct name {
	char str[100];
};
typedef struct name name;

#define phone 0x23451111
#define PHONE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define search 1
extern  customer * search_1(name *, CLIENT *);
extern  customer * search_1_svc(name *, struct svc_req *);
extern int phone_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define search 1
extern  customer * search_1();
extern  customer * search_1_svc();
extern int phone_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_customer (XDR *, customer*);
extern  bool_t xdr_name (XDR *, name*);

#else /* K&R C */
extern bool_t xdr_customer ();
extern bool_t xdr_name ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PHONE_H_RPCGEN */
