/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "phone.h"


void
phone_1(char *host)
{
	CLIENT *clnt;
	customer  *result_1;
	name  search_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, phone, PHONE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	char buffer[100][100];
	int counter[100] = {0};
	int index = 0;
	while(1) {
		int choice;
		printf("1.Search phone number\n2.Exit\n");
		scanf("%d",&choice);
		if(choice==1) {
			printf("Enter customer name: ");
			char cname[100];
			scanf("%s",cname);
			int location = -1;
			for(int i=0;i<index;i++) {
				if(strcmp(buffer[i],cname)==0) {
					location = i;
					break;
				}
			}
			if(location==-1) {
				strcpy(search_1_arg.str,cname);
				result_1 = search_1(&search_1_arg, clnt);
				if (result_1 == (customer *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else {
					if(strcmp(result_1->name,"NA")==0) {
						printf("Data not available\n");
					}
					else {
						printf("The data retrieved from server is:\n");
						strcpy(buffer[index++],result_1->name);
					}
					printf("Customer name: %s\n",result_1->name);
					printf("Customer phone number: %s\n",result_1->phone_number);
					printf("Customer address: %s\n",result_1->address);
				}
			}
			else {
				printf("Details already fetched!\n");
				printf("Number of times searched: %d\n",++counter[location] + 1);
			}
		}
		else if(choice==2) {
			printf("Bye! Thanks for using our service!\n");
			break;
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	phone_1 (host);
exit (0);
}