/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "phone.h"
#define N 4
customer *
search_1_svc(name *argp, struct svc_req *rqstp)
{
	static customer  result;  
	struct customer c[10];
	strcpy(c[0].name,"Vishnu");
	strcpy(c[0].phone_number,"7418529631");
	strcpy(c[0].address,"31/7A SV Layout");
	strcpy(c[1].name,"Balaji");
	strcpy(c[1].phone_number,"7894561231");
	strcpy(c[1].address,"31/8A VV Layout");
	strcpy(c[2].name,"Mani");
	strcpy(c[2].phone_number,"9874563211");
	strcpy(c[2].address,"31/9A WW Layout");
	strcpy(c[3].name,"Raghul");
	strcpy(c[3].phone_number,"7896523141");
	strcpy(c[3].address,"31/4A XX Layout");
	strcpy(c[4].name,"Sairam");
	strcpy(c[4].phone_number,"7412589631");
	strcpy(c[4].address,"31/6A YY Layout");
	int index = -1;
	for(int i=0;i<N;i++) {
		if(strcmp(argp->str,c[i].name)==0) {
			index = i;
			break;
		}
	}
	if(index!=-1) {
		strcpy(result.name,c[index].name);
		strcpy(result.phone_number,c[index].phone_number);
		strcpy(result.address,c[index].address);
	}
	else {
		strcpy(result.name,"NA");
		strcpy(result.phone_number,"NA");
		strcpy(result.address,"NA");
	}
	return &result;
}
