/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAT_H_RPCGEN
#define _CHAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct message {
	char m[1000];
};
typedef struct message message;

#define chat 0x23451111
#define CHAT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define send 1
extern  message * send_1(message *, CLIENT *);
extern  message * send_1_svc(message *, struct svc_req *);
extern int chat_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define send 1
extern  message * send_1();
extern  message * send_1_svc();
extern int chat_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message (XDR *, message*);

#else /* K&R C */
extern bool_t xdr_message ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHAT_H_RPCGEN */
