/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "chat.h"


void
chat_1(char *host)
{
	CLIENT *clnt;
	message  *result_1;
	message  send_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, chat, CHAT_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("Enter a text to send: ");
	scanf("%s",send_1_arg.m);
	result_1 = send_1(&send_1_arg, clnt);
	if (result_1 == (message *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("Server says: %s\n",result_1->m);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	chat_1 (host);
exit (0);
}
