/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"
void
calculator_prog_1(char *host,int num1,int num2,char operator)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  calculator_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULATOR_PROG, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	calculator_1_arg.a = num1;
	calculator_1_arg.b = num2;
	calculator_1_arg.c = operator;
	result_1 = calculator_1(&calculator_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("The result is: %d\n",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}
int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 5) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int num1 = atoi(argv[2]);
	int num2 = atoi(argv[3]);
	char operator = argv[4][0];
	calculator_prog_1 (host,num1,num2,operator);
exit (0);
}
