/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"
int *
calculator_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("The given choice is: %c\n",argp->c);
	printf("The given numbers are: %d %d\n",argp->a,argp->b);
	if(argp->c=='+') {
		result = argp->a + argp->b;
	}
	else if(argp->c=='-') {
		result = argp->a - argp->b;
	}
	else if(argp->c=='*') {
		result = argp->a * argp->b;
	}
	else {
		result = argp->a / argp->b;
	}
	return &result;
}
